name: TDR metadata checks lambda build release and deploy
on:
  push:
    branches:
      - main
    paths:
      - 'lambdas/tdr-draft-metadata-checks/**'
      - 'lambdas/tdr-draft-metadata-common/**'
      - 'build.sbt'
      - 'project/**'
  workflow_dispatch:

# Using a shared concurrency group across all workflows
concurrency:
  group: 'tdr-draft-metadata-validator-deploy'
  cancel-in-progress: false

jobs:
  pre-deploy-checks:
    uses: nationalarchives/tdr-github-actions/.github/workflows/lambda_build.yml@5d4fee21ed08f053613a7706e28623c0adc0f5f4 # v0.0.10
    with:
      repo-name: tdr-draft-metadata-validator
      lambda-name: draft-metadata-checks
      artifact-name: draft-metadata-checks
      artifact-path: lambdas/tdr-draft-metadata-checks/target/scala-2.13
      java-version: 21
      build-command: |
        sbt "tdrDraftMetadataChecks/assembly"
    secrets:
      MANAGEMENT_ACCOUNT: ${{ secrets.MANAGEMENT_ACCOUNT }}
      WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}

  deploy-checks:
    needs: pre-deploy-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Deploy lambda
        run: |
          gh workflow run deploy-lambda.yml --ref ${{ github.ref_name }} \
          -f environment=intg \
          -f to-deploy=${{ needs.pre-deploy-checks.outputs.next-version }} \
          -f lambda-name=draft-metadata-checks \
          -f deployment-package=draft-metadata-checks.jar
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
